### ISSUE TITLE
add easing-option for CSS-style cubic-bezier curves

### ISSUE THREAD

**Issue by s-light** [Eartz/animatePaper.js#13]
feature-request:
add support for  Cubic Bezier Curves for easing like in CSS.
so that it is possible to add the Bezier Values directly in the settings - something like
```
animatePaper.animate(itemXX, [
    {
        properties: {
            opacity: 1,
        },
        settings: {
            duration: 500,
            easing: BezierEasing(0, 0, 1, 0.5),
        }
    }
]);
```
(eventually namespace the BezierEasing class under the animatePaper global. but this eventually would prevent optimization for bundling...)
library i found that could help with this:
https://github.com/gre/bezier-easing

additional information on cubic bezier & easing & editors
http://cubic-bezier.com/#.2,0,.8,1
http://easings.net/

**Comment by camille-hdl** [comment]
in 1.2.1 you can pass a function `(p: number) => number` to `settings.easing`, so you will be able to use BezierEasing like in your example without having to use `.extendEasing()`.

I don't think I will add any new easing function directly into animatePaper as I think it makes more sense to me to pass them as an argument when needed.
At first, including the functions in the lib seemed like a good idea because 1) I could learn about easing and 2) jQuery did that and I used their animation API as a model, but in hindsight this is a very pre-modules approach and I should have just imported an existing easing lib.

Thanks for the suggestion !
cheers !
