### ISSUE TITLE
Browserify/AMD compatibility

### ISSUE THREAD

**Issue by not-only-code** [Eartz/animatePaper.js#2]
This library is using 'paper' as dependency, but if 'paper' is loaded through Browserify `paper` doesn't load, so try to use `require` also:

``` javascript
// line 5
var paper = global.paper; // require('paper');
```

**Comment by camille-hdl** [comment]
Hi, 
I'm not familiar with browserify.
Would something like

``` js
var paper;
if(typeof require === "function") {
    paper = require('paper');
}
else {
    paper = global.paper;
}
```

work with browserify, considering that theoretically the type of `require` can only be known at runtime and afaik browserify runs during the build process ?

**Comment by not-only-code** [comment]
Yeah something like this

**Comment by camille-hdl** [comment]
I'd appreciate if you could either test with the [latest version of the file](https://github.com/Eartz/animatePaper.js/blob/a036afcb0f97a96f4bca55d46cc21e744220f381/dist/animatePaper.js) or provide me an example so that I can try your configuration myself.

I'm simply doing a `require('paper')`, which should work if you have installed paper.js with npm.

cheers

**Comment by not-only-code** [comment]
For me its working, maybe u can tag it, i'm currently loading from master.
