### ISSUE TITLE
Support animation "loop"

### ISSUE THREAD

**Issue by StratusBase** [Eartz/animatePaper.js#5]
Could you please add basic support for looping animations?

Maybe add a new "loop" setting on the animation object that supports a true/false value for infinite / no loop [default]. Also, a "nice to have" would also be to support numeric values for _X_ number of loops.

Thanks!

**Comment by camille-hdl** [comment]
v1.0.1 includes `settings.repeat`, which can be used:

- with a number (repeat X additional times)
- with `true` (repeat until `.stop()` is called)
- with a function (repeat as long as the function returns `true`)

You can see examples [in the readme](https://github.com/Eartz/animatePaper.js#repeat).

I'll happily read your feedback if you want to try it 👍 

edit: I forgot to add that it should be used with relative values, because the animation doesn't "reset" the state of the item between runs
